language: cpp
compiler: gcc

dist: trusty
sudo: required

before_install:
    - sudo add-apt-repository --yes ppa:beineri/opt-qt561-trusty
    - sudo apt-get update -qq

install:
    - sudo apt-get install -y --force-yes qt56base qt56xmlpatterns qt56script qt56svg qt56declarative
    - sudo apt-get install -y --force-yes build-essential libglu1-mesa-dev

before_script:
    - source /opt/qt56/bin/qt56-env.sh


script:
    
    - /opt/qt56/bin/qmake lcd-image-converter.pro
    - make -j4
