github: [Repository metadata]
name: LCD Image Converter
url:              http://lcd-image-converter.riuson.com
baseurl:          http://lcd-image-converter.riuson.com
syntax-highlighting:
  enabled : true

author:
  name:           'Vladimir N'
  email:          riuson@gmail.com

resources:
  homepage:       http://www.riuson.com/lcd-image-converter
  repository:     https://github.com/riuson/lcd-image-converter
  downloads:      http://sourceforge.net/projects/lcd-image-converter/files

collections:
  wiki:
    output: true

exclude: [runserver.bat, runserver.sh]
